version: 2
jobs:
  branches:
    ignore:
      - gh-pages
  build:
    docker:
      - image: node:7.9
    working_directory: ~/trig
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - add_ssh_keys
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            fi
