version: 2
jobs:
  build:
    docker:
      - image: node:7.9 # Can't use alpine, git is needed to deploy
    branches:
      ignore:
        - gh-pages
    working_directory: ~/trig
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - add_ssh_keys
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email $CIRCLE_USERNAME
              git config --global user.name $CIRCLE_USERNAME
              npm run deploy
            fi
